services:
  - type: web
    name: detection-pleurs
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    runtime: python
    pythonVersion: python-3.9.13
